language: python
python:
  - "3.6"

notifications:
  email: false

install:
  - sudo apt-get update
  - sudo apt-get install mpich
  - python setup.py install

script:
  - python setup.py test
  # Test parallel running.
  #- mpirun -np 2 python tests/gaft_test.py

